### ISSUE TITLE
compile error on ARM

### ISSUE THREAD

**Issue by sma-ops** [NateBrune/fmem#14]
On an ARM 64 system with kernel 5.3.18-24.52, make runs into this issue (sorry for the missing newlines - I did not find out how I get newlines in code block working yet):

`
ccuser01@aarch64-arm-cc-niap:~/mem/fmem-master> make
rm -f *.o *.ko *.mod.c Module.symvers Module.markers modules.order \.*.o.cmd \.*.ko.cmd \.*.o.d
rm -rf \.tmp_versions
make -C /lib/modules/`uname -r`/build KBUILD_EXTMOD=`pwd` modules
make[1]: Entering directory '/usr/src/linux-5.3.18-24.52-obj/arm64/default'
  CC [M]  /home/ccuser01/mem/fmem-master/lkm.o
/home/ccuser01/mem/fmem-master/lkm.c: In function ‘my_xlate_dev_mem_ptr’:
/home/ccuser01/mem/fmem-master/lkm.c:99:25: **error: implicit declaration of function ‘ioremap_cache’**; did you mean ‘node_add_cache’? [-Werror=implicit-function-declaration]
  addr = (void __force *)ioremap_cache(start, PAGE_SIZE);
                         ^~~~~~~~~~~~~
                         node_add_cache
/home/ccuser01/mem/fmem-master/lkm.c:99:9: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  addr = (void __force *)ioremap_cache(start, PAGE_SIZE);
         ^
/home/ccuser01/mem/fmem-master/lkm.c: In function ‘my_unxlate_dev_mem_ptr’:
/home/ccuser01/mem/fmem-master/lkm.c:124:2: error: implicit declaration of function ‘iounmap’; did you mean ‘kunmap’? [-Werror=implicit-function-declaration]
  iounmap((void __iomem *)((unsigned long)addr & PAGE_MASK));
  ^~~~~~~
  kunmap
cc1: some warnings being treated as errors
make[3]: *** [/usr/src/linux-5.3.18-24.52/scripts/Makefile.build:282: /home/ccuser01/mem/fmem-master/lkm.o] Error 1
make[2]: *** [/usr/src/linux-5.3.18-24.52/Makefile:1650: _module_/home/ccuser01/mem/fmem-master] Error 2
make[1]: *** [../../../linux-5.3.18-24.52/Makefile:179: sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-5.3.18-24.52-obj/arm64/default'
make: *** [Makefile:12: fmem] Error 2
ccuser01@aarch64-arm-cc-niap:~/mem/fmem-master> uname -a
Linux aarch64-arm-cc-niap 5.3.18-24.52-default #1 SMP Tue Mar 2 13:15:25 UTC 2021 (c35b124) aarch64 aarch64 aarch64 GNU/Linux
ccuser01@aarch64-arm-cc-niap:~/mem/fmem-master> 
`

And just the error from above:
`/home/ccuser01/mem/fmem-master/lkm.c:99:25: error: implicit declaration of function ‘ioremap_cache’; did you mean ‘node_add_cache’? [-Werror=implicit-function-declaration]`
`addr = (void __force *)ioremap_cache(start, PAGE_SIZE);`
`                         ^~~~~~~~~~~~~`
`                         node_add_cache`

**Comment by hawk081** [comment]
you can try to add a header file.
```
#include <linux/io.h>
```

**Comment by sma-ops** [comment]
Thanks - with that it compiles properly. Unfortunately, running fmem does crash the system or produces a segfault. I now also read somewhere that fmem does not work for ARM (I should have checked that before ...)

**Comment by hawk081** [comment]
I tried it on a VIM3 board(a ARM board), dd also reports SegFault if trying to dump the whole RAM.

Maybe some addresses(regions) of the RAM are proteced, you can try to dump the RAM partially, not the whole.

**Comment by sma-ops** [comment]
I looked into lkm.c and tried to make use of the fact that it differentiates between RAM addresses and others, and tried to ignore non-RAM pages but that leads to throwing too much data away (and does not gather data that it actually should):

```
void *my_xlate_dev_mem_ptr(unsigned long phys)
{
        void *addr=NULL;
        unsigned long start = phys & PAGE_MASK;
        unsigned long pfn = PFN_DOWN(phys);

        /* If page is RAM, we can use __va. Otherwise ioremap and unmap. */
        if ((*guess_page_is_ram)(start >> PAGE_SHIFT)) {
                if (PageHighMem(pfn_to_page(pfn))) {
                        /* The buffer does not have a mapping.  Map it! */
                        addr = kmap(pfn_to_page(pfn));
                        return addr;
                }
                return __va(phys);
        }

       
        // --> Not RAM, so it is some device (can be bios for example)
        non_ram=1;
        return 0;
        /*
        addr = (void __force *)ioremap_cache(start, PAGE_SIZE);
        if (addr)
                addr = (void *)((unsigned long)addr | (phys & ~PAGE_MASK));
        return addr;
        */
       //<--
}
```

and in read_mem():

```
  ptr = my_xlate_dev_mem_ptr(p);

// --> just increse count when you hit non-ram page
                if (!ptr && non_ram==1) {
                        buf += sz;
                        p += sz;
                        count -= sz;
                        read += sz;

                        non_ram=0;
                        continue;
                }

 //<--
                if (!ptr) {
      ...
```
