### ISSUE TITLE
Unable to compile on - IBM AIX architecture

### ISSUE THREAD

**Issue by amarvind** [NateBrune/fmem#9]
Hi Team,

I am getting an error as mentioned below,  on running the make command as it is unable to compile 

make: Cannot find a rule to create target = from dependencies.

Looking forward to your answer
Cheers,

**Comment by NateBrune** [comment]
I don't believe that IBM AIX is compatible with linux kernel modules, and this project is not intended to support any kernel other than Linux. Unfortunately I will not be able to help.
